### ISSUE TITLE
Don't mention typed-process in Cabal description

### ISSUE THREAD

**Issue by ivan-m** [haskell/process#100]
In [this commit](https://github.com/haskell/process/commit/ad344892e2b745458c44ffcb079a52a274f683f2), you added a link to the new typed-process library.

Whilst I don't have a problem with that library, I think this is a contentious and surprising link to add:

* The `process` library is officially maintained by the libraries@haskell.org list, and as such I think any promotion of an alternative should be discussed and decided upon within that list.

* Furthermore, by linking to haskell-lang.org from a boot library, this provides it with an extra aura of authority, despite the fact that haskell-lang.org is not an official website for the Haskell language or community.

(Note: I don't think this was done maliciously, just with your "this is a much better library and here's a link to why you should use it" hat on.)

Whilst it may be beneficial to advise users that the typed-process library is safer/better, if it were to be mentioned from the process library (which I still think should be at least discussed on the mailing list) I think a more appropriate way of doing so is along the lines of "You may be interested in ..." and linking to the Hackage (and possibly Stackage) page for that library, which can then itself link to the tutorial.

**Comment by snoyberg** [comment]
I was specifically asked to add such a link to help people out, I was opposed to it initially.

**Comment by ivan-m** [comment]
May I ask by whom and why?

I don't have anything against typed-process, but for something to be semi-officially blessed as a solution in this way is a bit disquieting, especially as it then transitively blesses conduit for streaming; it's also only used by two packages as reported by Stackage, which makes it seem a bit un-battle-tested to be promoted in this way.

**Comment by snoyberg** [comment]
Example: https://www.reddit.com/r/haskell/comments/5w3jdg/the_typedprocess_library_what_to_do_with_it/de7icc4/

Let me say directly: I consider these kinds of discussions just about the most unpleasant kind to exist in package maintainership, and don't enjoy wasting time with them.

**Comment by erikd** [comment]
@snoyberg I really don't want to add to your pain here, but feel I need to weigh in.

I don't think anyone would complain if the text in the commit that @ivan-m references pointed to Hackage rather than the site it does.

Like @jwiegley I am very much in favor of improvements in this direction, especially ones that have been approved by the libraries committee and received more wide spread testing.

Be happy to buy you a beer (or even a scotch) in Oxford if that helps ease any pain involved in this kind of discussion.

**Comment by simonmar** [comment]
Agree with @erikd, let's adjust the link at the very least please.

**Comment by hvr** [comment]
It's curious to me, that first there was such a strong initial opposition to adding the link, which then was quickly overcome based on one suggested variant mentioned in a single comment, and now there's the dual opposition to revert this again (or at least defuse the controversy by amending the wording & link). Also, the irony isn't lost on me of this minor controversy resulting from making an "unilateral decision" on behalf of a package overseen by a committee... ;-)

That being said, to get back to a more constructive level: Given its current dependency footprint, `typed-process` has little chance to be used inside Cabal or GHC. In the long-term, I'd like to see some variant of Gershom's suggestion being implemented, i.e.  the "way forward would be adding it as an additional module, and encouraging both use". Maybe it's too early now to add this to `process` proper (to avoid frequent major ver bumps), but once the `typed-process` API has stabilized a bit more, I think it'd make sense to add a subset which doesn't require those extra non-core-deps to `process` proper.

**Comment by snoyberg** [comment]
That was a great comment, thank you @hvr. This wasn't "one suggested variant mentioned in a single comment," I only linked to one example. Feel free to look through the issue tracker, Reddit, and Twitter for further discussion. It's also completely disingenuous to present this as a "unilateral decision": I was placed as maintainer by the committee, and I asked for input from the outside before making this change, receiving no opposition.

As I said: I initially didn't want to do this. Enough people asked for the change and I did it. I'm adverse to change, period. And I'm adverse to wasting my time and the time of others. Multiple people were getting caught on issues in the process API that typed-process solved. Net time savings: done.  I'm opposed to the idea of going back and changing this for nebulous reasons. The link is currently to the official documentation for typed-process. I'm happy to discuss elsewhere why that page is the official documentation, but it's fully irrelevant to the discussion at hand.

I have no problem with moving ahead with the additional module here. I have no intention of adding a conduit dependency to the process package. There are still some issues that I believe need to be hashed out in typed-process with further testing before that can move forward (see issue tracker there for some recent changes, which uncovered a bug in process as well).

The only complaint mentioned here that I haven't addressed directly is the wording in the description which references typed-process. I frankly didn't spend much time thinking about it, and just looked at it again now. I see no problem with the wording as is; it correctly explains why someone would consider using an alternative library.

**Comment by jwiegley** [comment]
If the text is to stay, I also think the link should be changed. And it would be nice if it didn't read like an advertisement, and notice of deprecation of process.  Perhaps something more direct:

```
There is also a typed-process library under development which leverages the type system to avoid common pitfalls encountered when using this library. Although developed by a third party, you may find its approach useful: HACKAGE-LINK.
```

However, even this is unfair to all the other people who have written process replacements, such as `sys-process`. Even if typed-process is the best of them all, people will wonder why it suddenly is receiving preferential treatment, without any discussion on the libraries list.

**Comment by ekmett** [comment]
As a _suggestion_, it seems reasonable to adjust the link slightly as requested, but unlike @jwiegley seems to be arguing I don't feel any particular need to be "fair" to other variants of the same sort of package.

> I was placed as maintainer by the committee, and I asked for input from the outside before making this change, receiving no opposition.

Even if it were a "unilateral decision", we explicitly have a policy of allowing action by maintainers --
 it is why we have them in the first place -- so you're totally in the clear.

**Comment by jwiegley** [comment]
@ekmett Good enough for me. It looks like all anyone is asking for is a link change then?
