### ISSUE TITLE
Bug with `terminateProcess` and `shell`

### ISSUE THREAD

**Issue by elliottt** [haskell/process#115]
The documentation for `terminateProcess` says the following, regarding killing processes created with the `shell` combinator:

> On Unix systems, both processes are in a process group and will be terminated together.

However, the implementation of the `terminateProcess` function in [runProcess.c](https://github.com/haskell/process/blob/master/cbits/runProcess.c#L379-L383) does not appear to  do that, as it will never pass a negated process id to the `kill` syscall [(the relevant man page section for kill)](http://man7.org/linux/man-pages/man2/kill.2.html#DESCRIPTION). After reading through the library, there doesn't appear to be a code path that would internally negate the process  id that is held within the `ProcessHandle`.

To illustrate the problem, this program will leave a `sleep` process running, after killing off the `/bin/sh` process that starts it (note that it's important to build this with the threaded runtime):

```haskell
import Control.Concurrent
import Control.Exception
import System.IO
import System.Process

main =
  do tid <- forkIO $
       do (_,_,_,ph) <- createProcess (shell "sleep 100")
          waitForProcess ph `finally`
            do putStrLn "TERMINATING!"
               terminateProcess ph

          return ()

     threadDelay 1000000
     killThread tid
```

Additionally, using the `interruptProcessGroupOf` instead of `terminateProcess` in the program above will successfully kill the entire process group. It's worth pointing out that `interruptProcessGroupOf` uses a different syscall to kill the group, `killpg` instead of `kill` with a negated process id.

**Comment by snoyberg** [comment]
It seems like the most direct fix here is a doc fix, clarifying that users should use `interruptProcessGroupOf` when using the `shell` function. Did you have something else in mind?

**Comment by elliottt** [comment]
Agreed, that is the most direct fix. However, the functionality described in the documentation does seem desirable, so I would prefer that the implementation be changed to fit the original intent.

To that end, it seems reasonable to me to keep a `Bool` in the `OpenHandle` constructor that mirrors the value of the `create_group` field from the `CreateProcess` value that was used to start the group. This value could be used to decide whether or not to negate the pid when dispatching to the `kill` syscall.

**Comment by snoyberg** [comment]
I'm wary of making such a change. It will lead to some level of code breakage (mitigated by the fact that this only affects internal modules). But more importantly, this can lead to perhaps surprising behavior where `terminateProcess` behaves completely differently for, e.g. `shell "foo bar"` versus `proc "bash" ["-c", "foo bar"]`, as well as large differences in runtime behavior between process versions without affecting the public API.
