### ISSUE TITLE
`System.Process.terminateProcess` on Windows

### ISSUE THREAD

**Issue by rockbmb** [haskell/process#116]
Hello; firstly I'd like to point out that I browsed the list of open issues, and none seems to fit the problem I've run into.

Here's my situation.

* In [this](https://github.com/haskell/process/blob/master/System/Process.hs#L731) line of documentation, it says that on Windows [`System.Process.terminateProcess`](https://github.com/haskell/process/blob/master/System/Process.hs#L740) uses the [TerminateProcess](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686714(v=vs.85).aspx) function of the `Win32` API.

However, from the source code we can see this is not the case:
* In [this](https://github.com/haskell/process/blob/master/System/Process.hs#L746) line of the implementation, we can see that [`terminateJob`](https://github.com/haskell/process/blob/master/System/Process/Windows.hsc#L186) is used instead.
* Further, `terminateJob` uses the [`TerminateJobObject`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686709(v=vs.85).aspx) function from the `Win32` API.
* This is instead of actually using the [`TerminateProcess`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686714(v=vs.85).aspx`) function mentioned in the Haddock docs.

What is the reason for this? Is the use of `TerminateJobObject` intended and the documentation incorrect, is the documentation right and the function's use incorrect, or something not explained in the comments? In any case, can this (possible) confusion cause any issues with process termination on Windows?

I apologize if there's something glaringly obvious I'm missing.

I'd like to thank whoever looks at this issue in advance for the time taken to do so.

**Comment by snoyberg** [comment]
@Mistuke I was wondering if you might have some input here.
