### ISSUE TITLE
handles seem to be ignored

### ISSUE THREAD

**Issue by vwwv** [haskell/process#118]
So I was trying to span a new process, and communicate with it bidirectionally through 2 pipes, like:
```
do (readToProcess  , writeToProcess)   <- createPipe
   (readFromProcess, writeFromProcess) <- createPipe
   _ <- createProcess_ "porc" (proc cmd cmdArgs)
          { std_in      = UseHandle readToProcess
          , std_out     = UseHandle writeFromProcess
          , close_fds   = False
          }

   hPutStr writeToProcess "hi process !" >> hFlush writeToProcess
   forever $ putText =<< hGetLine readFromProcess 
``` 
But it just won't communicate, neither way....not sure what the issue is, so sorry if it is not related, but I think it might be. Surprisingly,  if I use `hGetContents` instead of `hGetLine`, it will briefly work, both ways! but it will become semi-closed.

**Comment by vwwv** [comment]
My apologies, it was something else, I'm closing this.

**Comment by RyanGlScott** [comment]
> can somebody delete this issue ?.

Sure thing :)
