### ISSUE TITLE
readProcess fails when stdout contains non-ASCII symbols

### ISSUE THREAD

**Issue by cuklev** [haskell/process#127]
Hi,

Calling a command which outputs non-ASCII symbol results in exception. Here is an example:

```
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
Prelude> :m +System.Process
Prelude System.Process> readProcess "bash" ["-c", "printf %c \160"] ""
*** Exception: fd:13: hGetContents: invalid argument (invalid byte sequence)
Prelude System.Process>
```

**Comment by snoyberg** [comment]
The String based functions have this limitation. You should instead work directly with the underlying Handle and use binary I/O. Alternatively, the typed-process package provides an alternative API which makes it easier to work with ByteStrings.

**Comment by cuklev** [comment]
Thanks for the package suggestion!

Is it just a limitation, though? Here is an example which does not fail:
```
Prelude System.Process> readProcess "cat" [] "\160"
"\160"
```
Why do some commands work and others don't?

**Comment by cuklev** [comment]
Okay, seems like `printf %c "<MULTIBYTE CHAR>"` prints just the first byte of the `<MULTIBYTE CHAR>`, which is not a valid symbol and causes the error.

**Comment by snoyberg** [comment]
Is this issue good to close?

**Comment by cuklev** [comment]
Yes.
