### ISSUE TITLE
createProcess function is can't exec a *.cmd or *.bat file

### ISSUE THREAD

**Issue by taiju** [haskell/process#140]
-- Sorry, I'm poor English.

createProcess function is can't exec a *.cmd or *.bat file.

I can exec `foo` command when `foo.cmd` is placed of system environment variable paths. However, createProcess function is can't exec `foo`. (`foo.cmd` too)

It catch an error that error message is `does not exist (No such file or directory)`.

## reproduction screenshot

![ps](https://user-images.githubusercontent.com/95721/48598970-fe98bb80-e9a8-11e8-996c-1b2ac8986b24.png)

## about this problem

This is not usually a problem. However, It may be a  problem. For example, some of the commands built by NodeJS (with NPM) are wrapped with .cmd file.

- SEE
    - https://docs.npmjs.com/misc/config#bin-links
    - https://github.com/npm/cmd-shim
    - https://github.com/npm/bin-links

Concretely, I'm facing this problem at <a href="https://github.com/purescript/psc-package/issues/34">here</a>.

**Comment by taiju** [comment]
There is `Path` env var set. `bin` subdirectory is included it.

![env-path](https://user-images.githubusercontent.com/95721/48680350-fbd2dc00-ebdd-11e8-9902-369ef55de4d7.png)

the env var passed in to `ghci`.

![getenv](https://user-images.githubusercontent.com/95721/48680367-186f1400-ebde-11e8-98b5-8363a68e1824.png)

`proc "foo.cmd"` instead work.

Although it can be executed on the command line, it can not be executed on the `createProcess` in some cases.

![results](https://user-images.githubusercontent.com/95721/48682092-e2d02800-ebe9-11e8-9f44-5a4a4862af83.png)

※ `指定されたパスが見つかりません` means "The specified path can not be found".

**Comment by snoyberg** [comment]
OK, so narrowing this down further, it seems like the problem is: given a plain executable name like `foo`, the process package will find `foo.exe` if it exists in directories of the `PATH`, but it will _not_ find `foo.bat` and `foo.cmd`. Is that accurate?

**Comment by taiju** [comment]
Yes, it is accurate.
Additionally, createProcess can't resolve cwd path in `foo.cmd` well such as a screen shot above.

**Comment by snoyberg** [comment]
I've looked into the source code on Windows. Ultimately, we're passing the command line to the `CreateProcess` function, which seems to document this behavior:

> If the file name does not contain an extension, .exe is appended. Therefore, if the file name extension is .com, this parameter must include the .com extension. If the file name ends in a period (.) with no extension, or if the file name contains a path, .exe is not appended.

(From [MSDN on CreateProcessA](https://docs.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-createprocessa).)

I don't see which screen shot demonstrates the claim about the CWD path. I will note that on POSIX systems, that's the expected behavior. However, from the same MSDN docs, it _should_ work as you expect on Windows:

> If the file name does not contain a directory path, the system searches for the executable file in the following sequence:
>
> 1. The directory from which the application loaded.
> 2. The current directory for the parent process.

**Comment by taiju** [comment]
> I don't see which screen shot demonstrates the claim about the CWD path.

I'm sorry for bad explanation. Please see below.

![path](https://user-images.githubusercontent.com/95721/48694424-97387100-ec1f-11e8-8fe8-a349ed386e9c.png)

I expected `%~dp0` output result point to the path of `foo.cmd`. However, `%~dp0` point to the `ghci` CWD path. (I couldn't found official informations of `%~dp0`.)

**Comment by snoyberg** [comment]
I'm going to guess in all of these cases, if you instead use `shell` (not `proc`), you get the behavior you're looking for. If that's the case, I would say that the library is acting as expected.

**Comment by taiju** [comment]
Thank you! `shell` is acting as expected!
I understood that the problem that I'm facing is not a `System.Process` library problem, but a `System.Process` library user side problem.

**Comment by snoyberg** [comment]
You're welcome, no problem
