### ISSUE TITLE
SIGINT ignored after a failed callProcess

### ISSUE THREAD

**Issue by DaveCTurner** [haskell/process#15]
On Linux, the following program does not exit on SIGINT. If `"does-not-exist"` is replaced with a program that does exist (e.g. `"echo"`) then it continues to respond to SIGINT.

    import Control.Concurrent
    import Control.Exception
    import Control.Monad
    import System.IO
    import System.Process

    ignoreIOException :: IOException -> IO ()
    ignoreIOException _ = return ()

    main = do
      _ <- forkIO $ callProcess "does-not-exist" [] `catch` ignoreIOException
      _ <- getLine
      return ()

Unlike with https://github.com/haskell/process/pull/14 (which may well be related - it's a similar test case) I am at a loss as to what the fix might be!

**Comment by dcoutts** [comment]
Good catch. I've got a fix.

**Comment by hvr** [comment]
Please re-open if this isn't fixed by #16

**Comment by DaveCTurner** [comment]
Just to confirm, it's fixed by #16.

Thanks,
