### ISSUE TITLE
add pass_fds argument to CreateProcess

### ISSUE THREAD

**Issue by complyue** [haskell/process#158]
Please consider adding an argument to CreateProcess named `pass_fds`, which specifies a list of fds in addition to stdin/out/err to be passed to the subprocess, then other fds should not be inherited by the started subprocess. 

And seems `pass_fds` will be semantically mutually exclusive with the existing `close_fds`.

## Background

In a traditional [inetd](https://en.wikipedia.org/wiki/Inetd) style multiprocessing architecture, incoming connections are accepted by a shared parent process, and each new connection will trigger a subprocess to be spawned with stdio hooked to the socket of the new connection. 

I'm implementing a similar architecture, but the underlying connection is [websocket](https://en.wikipedia.org/wiki/WebSocket), so it's not appropriate for the `stdin/stdout/stderr` to be hooked to the websocket, as the traffic will be a mix of textual and binary packets, not a pair of binary streams or uniformly encoded text streams.

To launch subprocesses in Haskell this way, I have written the parent process in Python/asyncio so far so good, like:

```python
async def start_socket_handler(
    cs: socket.socket,
    exe: str = "/usr/bin/env",
    # build & run the default executable of the stack project at cwd by default
    cmdl: Sequence[str] = ("env", "stack", "run", "--", "{sock_fd}"),
    cwd: Optional[str] = None,
) -> Awaitable[asyncio.SubprocessTransport]:
    """
    start a subprocess with the connected socket
    """

    loop = asyncio.get_running_loop()

    try:

        sock_fd = cs.fileno()

        popen_args = [
            s.format(sock_fd=sock_fd) if isinstance(s, str) else str(s) for s in cmdl
        ]
        popen_kwargs = dict(executable=exe, pass_fds=(sock_fd,), cwd=cwd)

        fut = loop.create_future()
        await loop.subprocess_exec(
            lambda: UpstartProtocol(fut),
            # args passing through to Popen
            *popen_args,
            # upstarted subprocesses have not input, shares output with parent process
            stdin=asyncio.subprocess.DEVNULL,
            stdout=None,
            stderr=None,
            # kwargs passing through to Popen
            **popen_kwargs,
        )

        return fut

    finally:
        # close the socket in this parent python process anyway
        cs.close()

```

But I'd like to rewrite the parent process in Haskell to simply things further, and I can't find a counter part in Haskell, to the `pass_fds` parameter of Python's [Popen](https://docs.python.org/3/library/subprocess.html#subprocess.Popen) API.

The closest thing I discovered so far, is the `close_fds` parameter in [CreateProcess](https://www.stackage.org/haddock/lts-14.9/process-1.6.5.0/System-Process.html#t:CreateProcess), despite it seemed some stu**d (no offending intended but forgive me for being frank in expressing my first impress) to try closing all fds `[3..max_fd]`, that's still not what I really need.

I can live with that all fds get inherited by all subprocesses, as in my current use cases, but that's  leaking the listening socket into every subprocesses ever started. I know Haskell is not systems programming oriented, but this feels reasonably to be improved.

Did I miss something ?

**Comment by complyue** [comment]
A side note that even in Python, it needs some tweaks like [forkeserver](https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods), to be free of fd-leaking in complex cases. But `pass_fds` solved simple cases well enough.

**Comment by snoyberg** [comment]
Please try to rephrase this into a concrete request. There seems to be a lot of extraneous information and unwarranted opinion.

**Comment by complyue** [comment]
in proceeding of my prototyping, I learned that current norm is to set FD_CLOEXEC on sockets and open files with O_CLOEXEC, I'm sure 'network' package is already doing this by default, but not sure if file open in ghc already set O_CLOEXEC by default. anyway, as long as all fds are properly set to be closed on exec, all is good.

so no need for pass_fds really, and close_fds may even be deprecated then removed I suppose. closing.
