### ISSUE TITLE
Build failes on windows

### ISSUE THREAD

**Issue by jdkr** [haskell/process#175]
The build process failes for newer versions on windows. Here is the error message:
```
Failed to build process-1.6.8.2. The failure occurred during the configure
step.
Build log (
C:\Users\jodak\AppData\Roaming\cabal\logs\ghc-8.8.1\process-1.6.8.2-1f00999bf06e21c746c76a17ea5ef5a94df6efb8.log
):
Configuring process-1.6.8.2...
cabal.exe: The package has a './configure' script. If you are on Windows, This
requires a Unix compatibility toolchain such as MinGW+MSYS or Cygwin. If you
are not on Windows, ensure that an 'sh' command is discoverable in your path.
```

The Bug seems to occur in version 1.6.6.0:
* process-1.6.5.1 -> OK
* process-1.6.6.0 -> failed
* process-1.6.8.2 -> failed

My setting is:
* Windows10x64
* ghc-8.8.1 (build with flag: INTEGER_LIBRARY=integer-simple)
* cabal-install-3.2.0.0_x86_64

**Comment by snoyberg** [comment]
Building `process` has to my knowledge always required a shell, it's part of the design we made in MinGHC and later in Stack. Are you sure you were able to build process-1.6.5.1 yourself, as opposed to simply getting it in the GHC bindist?

**Comment by jdkr** [comment]
Yes, I think you're right. If I set `process == 1.6.5.1` in my cabal file, it only seems to be included and not compiled. Here's the part of the log:

```
Component graph for hsc2hs-0.68.6: component exe:hsc2hs
component hsc2hs-0.68.6-c3cccdea8e26d4f56f98fcb3739d3c85e70a2894
    include base-4.13.0.0
    include containers-0.6.2.1
    include directory-1.3.3.2
    include filepath-1.4.2.1
    include process-1.6.5.1
unit hsc2hs-0.68.6-c3cccdea8e26d4f56f98fcb3739d3c85e70a2894
    include base-4.13.0.0
    include containers-0.6.2.1
    include directory-1.3.3.2
    include filepath-1.4.2.1
    include process-1.6.5.1
```

**Comment by snoyberg** [comment]
Got it. Closing as this is acting as expected.

**Comment by jdkr** [comment]
So the bug is somewhere else, like in Cabal? Should Cabal have binaries available for every package that require some extra tools for compilation where the build can possibly fail?

**Comment by ndmitchell** [comment]
As a general rule, if you have difficulty compiling a thing that uses configure scripts on Windows, either switch to the very latest Cabal (sometimes works) or switch to Stack (always works). Haskell doesn't really do binary distributions, so you could say perhaps Cabal should work that way, but it's a very long way from how it currently works.
