### ISSUE TITLE
`createPipe` doesn't work on Windows

### ISSUE THREAD

**Issue by TerrorJack** [haskell/process#181]
Example program:

```haskell
{-# LANGUAGE OverloadedStrings #-}

import qualified Data.ByteString as BS
import System.IO
import System.Process

main :: IO ()
main = do
  (h_read, h_write) <- createPipe
  let msg = "233"
  BS.hPut h_write msg
  hFlush h_write
  BS.hGet h_read (BS.length msg) >>= print
```

This prints `"233"` on Linux/macOS, but the program hangs indefinitely on Windows. Tested against `ghc-8.10.1` which ships `process-1.6.8.2`, both on my Windows 10 laptop and on [GitHub Actions](https://github.com/tweag/inline-js/runs/741183886?check_suite_focus=true).

**Comment by snoyberg** [comment]
I don't have easy access to a Windows machine right now to test this out, and honestly don't have any ideas on what might be causing this. @Mistuke any thoughts?

**Comment by Mistuke** [comment]
@snoyberg #182 fixes this. The code isn't broken it's just the buffer size is ridiculously low.

The write above blocks and is waiting for the read to drain it. but since everything is done on the same thread the program deadlocks.

**Comment by TerrorJack** [comment]
@snoyberg I just validated locally and @Mistuke's patch works, with threaded/non-threaded runtime. Would be nice to have a minor release for the bugfix. Thanks for the timely patch :D

**Comment by snoyberg** [comment]
Released on Hackage. Thanks @Mistuke!
