### ISSUE TITLE
Process argument encoding issue?

### ISSUE THREAD

**Issue by jtdaugherty** [haskell/process#187]
I'd love some help understanding what is going on here. I don't know if this is a bug. Given the following test program where I want to invoke a subprocess with an argument containing Unicode characters,
```haskell
import System.Process

main :: IO ()
main = do
    let o = proc "/bin/cat" ["😅"]
    (_in, _out, _err, ph) <- createProcess o
    ec <- waitForProcess ph
    print ec
```
the (expected) behavior with `LANG=en_US.UTF-8` is
```
$ runhaskell proc.hs
/bin/cat: 😅: No such file or directory
ExitFailure 1
```
and the (unexpected to me) behavior with `LANG=it_IT.UTF-8` is
```
$ LANG=it_IT.UTF-8 runhaskell proc.hs
proc.hs: /bin/cat: recoverEncode: invalid argument (invalid character)
```
In particular, I don't understand why the second example behaves as it does. I would expect that to work. Can you shed some light on this?

**Comment by jtdaugherty** [comment]
Also, I neglected to mention: this is on Ubuntu 18.04.2 LTS, GHC 8.0.2, process 1.4.3.0.

**Comment by snoyberg** [comment]
Have you generated all relevant locale files on that machine?

**Comment by jtdaugherty** [comment]
After I added `it_IT` to `/etc/locale.gen` and re-ran `locale-gen`, the test program behaved as I expected. Thank you! Can you provide any detail about what is going on under the hood to result in the above behavior?

**Comment by snoyberg** [comment]
If you haven't seen it, this blog post is my best explanation of the lower-level mechanisms:

https://www.snoyman.com/blog/2016/12/beware-of-readfile

My guess in this case is that:

* GHC runtime system sees LANG var
* It looks for locale settings for it_IT
* It can't find anything, so it (IMO dumbly) falls back to ASCII
* ASCII encoding fails

**Comment by jtdaugherty** [comment]
Okay, that makes sense to me. Thanks for your help!
