### ISSUE TITLE
Reading from arbitrary fds

### ISSUE THREAD

**Issue by re-xyr** [haskell/process#191]
Hi,
I want to read from an fd different from 1 and 2. I have searched the docs and did not find a relevant API. Is it possible to do this?

**Comment by snoyberg** [comment]
The question is unclear, but I'm guessing you're looking for a way to specify the stdin, stdout, or stderr of a child process. You can use the `UseHandle` data constructor (see https://www.stackage.org/haddock/nightly-2020-08-23/process-1.6.9.0/System-Process.html#t:StdStream). You'd need to also use something like [`fdToHandle`](https://www.stackage.org/haddock/lts-16.10/base-4.13.0.0/GHC-IO-Handle-FD.html#v:fdToHandle).

**Comment by re-xyr** [comment]
Hi @snoyberg ,

Sorry for the ambiguity, the case is that I need to call an application that produce most of its output to fd 1 and 2 (stdout, stderr) but some other to fd 3 (which is none of the three handles provided by `createProcess`). Therefore, I want to read from fd 3 of *the child process* (in Node.js I can do this by `ChildProcess.stdio[3]`).

I could have redirected fd 3 to fd 1 (by `3>&1`), but that will make it impossible to distinguish different kinds of outputs.

**Comment by snoyberg** [comment]
There's no high level API for doing this in the library. You would have to use lower level functions to create the pipes and `dup2` them to the desired file descriptors.

**Comment by re-xyr** [comment]
@snoyberg Got it, thanks!
