### ISSUE TITLE
How to read stdout of a spawned process?

### ISSUE THREAD

**Issue by GilmarCorreia** [haskell/process#197]
Hello, Haskell community,

I'm trying to emulate a Command Prompt with Haskell and Threepenny-Gui, it's working well, I'm getting the std_out correctly, but when I use createProcess I get stuck in the process until it is finished.

Is there any way that I can read the std_out of a process while it keeps running? (like a python code with a time.sleep(2))

**Comment by snoyberg** [comment]
The short answer is: yes, you can do that. But without knowing what you've tried, we can't provide any more insight.

**Comment by GilmarCorreia** [comment]
I'm trying doing this:

```haskell
printBox :: Window -> String -> String -> UI ()
printBox window cmdText arg = do
  parText <- getElementById window "cmdText"
  cd <- liftIO getCurrentDirectory
  cmdOldText <- get UI.value (unbox parText)
  let cmdNewText = cmdOldText ++ " " ++ cmdText ++ "\n" ++ arg ++ "\n" ++ cd ++ ">"

  return (unbox parText) # set UI.text cmdNewText
                         # set UI.value cmdNewText

  return ()

tryCommand :: Window -> String -> UI ()
tryCommand window cmdText = do  
  let textSplit = words cmdText
      config = (proc (head textSplit) (tail textSplit)) {
        std_out = CreatePipe,
        std_err = CreatePipe
      }
  result <- (liftIO $ try (createProcess_ "spawnedProcess" config))  :: UI (Either IOException (Maybe Handle, Maybe Handle, Maybe Handle,ProcessHandle))
  case result of
    Left exc -> do
      printBox window cmdText $ show exc ++ "\n"

    Right (inp, out, err, pid) -> do
      stdout' <- liftIO $ case out of 
                            Nothing -> return ""
                            (Just x) -> hGetContents x
      printBox window cmdText stdout'

```

test.py
```python
import time

print("test 1")
time.sleep(2)
print("test 2")
time.sleep(2)
```

tryCommand receives a ThreePenny Window and a command Like "python test.py". After analyzing the result exception, it updates the printBox, which is an HTML P element.  I'm trying all the ways to avoid deadlock, but unsuccessfully.

**Comment by Fuuzetsu** [comment]
I think this may help you: https://stackoverflow.com/questions/61699509/haskell-hgetcontents-blocking-problem-reading-more-lines

**Comment by GilmarCorreia** [comment]
Thank you @Fuuzetsu, I've tried using hGetLines instead of hGetContents with async processes, but it doesn't seem to work properly with this application, and the same problem still happening, the process needs to close to be able to get the results from stdout.

**Comment by Fuuzetsu** [comment]
> Thank you @Fuuzetsu, I've tried using hGetLines instead of hGetContents with async processes, but it doesn't seem to work properly with this application, and the same problem still happening, the process needs to close to be able to get the results from stdout.
> 
> …

I don't know about your `runUI` stuff etc but the `process` bits should be working. Here's a simple program I made:
```haskell
module Main (main) where

import System.Process
import System.IO (hGetContents, hGetLine)
import Data.Time.Clock (getCurrentTime)
import Prelude hiding (log)

main :: IO ()
main = do
    (_, Just h, _, ph) <- createProcess (proc "bash" ["-c", "for i in $(seq 1 5); do echo $i; sleep 1; done;"])
        { std_out = CreatePipe }
    let loop = do
            text <- hGetLine h
            log $ "Got line from process: " <> text
            m'exitCode <- getProcessExitCode ph
            case m'exitCode of
                Nothing -> loop
                Just{} -> do
                    lastText <- hGetContents h
                    log $ "Process exited, last content: " <> lastText
    loop
    where
        log msg = do
            t <- getCurrentTime
            putStrLn $ show t <> " - " <> msg
```
and you can see it working here:
```console
[nix-shell:/tmp]$ ghc -O2 /tmp/P.hs 
[1 of 1] Compiling Main             ( /tmp/P.hs, /tmp/P.o )
Linking /tmp/P ...

[nix-shell:/tmp]$ ./P 
2020-12-14 23:42:12.166459019 UTC - Got line from process: 1
2020-12-14 23:42:13.167368526 UTC - Got line from process: 2
2020-12-14 23:42:14.168388122 UTC - Got line from process: 3
2020-12-14 23:42:15.16935645 UTC - Got line from process: 4
2020-12-14 23:42:16.170301882 UTC - Got line from process: 5
P: fd:3: hGetLine: end of file
```

We can get a line at at time from the process no problem, before it terminates.

**Comment by GilmarCorreia** [comment]
Thank you @Fuuzetsu, this code is working for me. The problem is when I try to run a python code, as an example test.py:

```python
import time

print("test 1")
time.sleep(2)
print("test 2")
time.sleep(2)
```

and then in haskell:

```haskell
(_, Just h, _, ph) <- createProcess (proc "python" ["test.py"])
        { std_out = CreatePipe }
```

This was my result from the terminal:

```shell
2020-12-15 15:43:41.4196592 UTC - Got line from process: test 1
2020-12-15 15:43:41.4234018 UTC - Got line from process: test 2
teste: fd:3: hGetLine: end of file
```

**Comment by GilmarCorreia** [comment]
I've found my mistake. I need to run the python3 command with -u flag. Now it's working. Thank you so much!
