### ISSUE TITLE
Structuring Turtle.Prelude

### ISSUE THREAD

**Issue by yaccz** [haskell/process#20]
Hi,

It would be nice to structure Turtle.Prelude by the package name the utilities originaly come from. So we would have something like Turtle.Prelude.{Builtins,Coreutils,...}

**Comment by snoyberg** [comment]
I think you made this issue on the wrong repo.

**Comment by yaccz** [comment]
Oh crap, you are right. Sorry.

**Comment by snoyberg** [comment]
No problem it happens :)
