### ISSUE TITLE
environment setting stopped working on DragonFly BSD

### ISSUE THREAD

**Issue by joeyh** [haskell/process#223]
I have a report that on Dragonfly BSD, process fails to set environment variables at all. The problem is with the version bundled with ghc 8.10.7, while 8.10.5 works ok.

Seems likely related to https://github.com/haskell/process/issues/219

The user confirmed that this test case outputs "testing: "

      import System.Process
   
      main = do
              let p = (proc "sh" ["-c", "echo testing: $TEST"])
              let p' = p { env = Just [("TEST", "foo")] }
              withCreateProcess p' $ \_ _ _ pid -> waitForProcess pid

**Comment by joeyh** [comment]
Note that the test case works correctly on Linux with the same ghc version.

**Comment by falsifian** [comment]
It's a DragonflyBSD bug, so this can be closed. @zrj-rimwis is testing a fix in dfly.

**Comment by snoyberg** [comment]
Thanks for confirming
