### ISSUE TITLE
Process 1.6.13 changed observable behaviour

### ISSUE THREAD

**Issue by angerman** [haskell/process#227]
Reproducer is https://github.com/angerman/repro-process-behaviour-change-1.6.13

Will produce the following output:
```sh
$ make all CABAL=$(which cabal) GHC=$(which ghc)
Building against process < 1.6.13 ...
Running against process < 1.6.13; with an empty PATH, this should result in a git not found message
<no git executable found>
Building against process >= 1.6.13 ...
Running against process >= 1.6.13; this now throws an exception instead.
process-crash: git: readCreateProcessWithExitCode: posix_spawnp: failed (Undefined error: 0)
make: *** [Makefile:9: all] Error 1
```

We are now throwing an exception where we didn't before.

**Comment by bgamari** [comment]
Thanks @angerman, I'll investigate!

**Comment by bgamari** [comment]
Which operating system is this reproducible on?

**Comment by bgamari** [comment]
I cannot reproduce this on Linux. 

Speaking to @angerman, it seems that they only see this on Darwin.

**Comment by bgamari** [comment]
@angerman says that `posix_spawnp` returns 2. However, the log output clearly suggests that `errno==0`. The problem appears to be that Darwin's `posix_spawnp` implementation does not set `errno` whereas glibc's appears to. This is the source of the discrepancy.
