### ISSUE TITLE
Spawned threads die from SIGINT eariler than Haskell thread

### ISSUE THREAD

**Issue by Martoon-00** [haskell/process#236]
## Description

In case the Haskell application is interrupted, the spawned threads also receive `SIGINT`, and they usually die from it earlier than the parent Haskell thread. This leaves me with less control when desired.

For instance, if I want to get the output of the spawned process, I may end up in a situation when the spawned thread just died, but the code that collects the output is yet running, and there is nothing sensible I could do (neither return, nor throw an exception). 

To reproduce: running [this example](https://gist.github.com/Martoon-00/18139b31ed4e4e86ff7f9cef9772d60f) I get 

```
Connected, getting
^CAwaited: ExitFailure (-2)
Result: 17121280
```

This is reproduced on two MacOS and one Ubuntu machines, with `process-1.6.13.2`.

So the spawned thread dies with `ENOENT`, in the parent thread I can wait until getting `SIGINT`  too but in the general case this does not sound like a working strategy.

What would be the best way thing to do in my use case?

**Comment by snoyberg** [comment]
This is the intended POSIX behavior and not Haskell specific. For more information, see https://stackoverflow.com/questions/6803395/child-process-receives-parents-sigint

**Comment by Martoon-00** [comment]
Yeah, I see. 

The answer in that SO question proposes wrapping `execl` into some C code to prevent the child process from getting the `SIGINT` targetted to my process. So if I want to support my scenario, I will need a patch in `system` library that would allow me spawning a process in this special way? Currently there is `delegate_ctlc` flag, and I need sort of the opposite thing. 

Or better seek for a completely different solution, and not try to spawn such a process from within Haskell?

**Comment by snoyberg** [comment]
I haven't tried this myself but you could try creating a new process group with the `create_group` flag.

**Comment by Martoon-00** [comment]
Oh, I somehow missed that flag :facepalm:  

It indeed fixed my case, thanks!
