### ISSUE TITLE
Support for other string types like Text and ByteString (strict and lazy)

### ISSUE THREAD

**Issue by malteneuss** [haskell/process#265]
Do functions like `runProcess` and `callProcess` support other string types ofr inputs and outputs? If not, could or should they? E.g. for convenience and performance. For example, want to call run a command the returns JSON. But in order to decode it with e.g. Aeson i have to convert the returned String to lazy ByteString, which requires an awkward conversion chain through lazy Text:
```haskell
import Data.Text.Lazy             as TL
import Data.Text.Lazy.Encoding    as TL

-- String -> BL.Bytestring
fromString = TL.encodeUtf8 . TL.pack
```

**Comment by snoyberg** [comment]
We've considered it in the past, and the general answer is no. The string-based APIs themselves generally aren't a good idea either, but they're more deeply hard-coded. For interacting with input/output, you should work directly with the `Handle`s. Alternatively, the `typed-process` package provides a higher level API for many common use cases.
