### ISSUE TITLE
Hackage bump request due critical bug in recent version

### ISSUE THREAD

**Issue by Heather** [haskell/process#27]
Currently this pull request is critical on windows: https://github.com/haskell/process/pull/21

I just can't build recent process from hackage right now.
I can verify that current master builds / works well for me.

Thank you

**Comment by snoyberg** [comment]
@hvr Would you be able to make a release to Hackage? Alternatively, I can try and make my first process release, if you'd prefer to have me take over that role now.

**Comment by hvr** [comment]
@snoyberg well, if you have time, I'll rather guide you through the steps:

1. `cabal sdist` & upload it as candidate to Hackage
2. `git tag -a -s -m 'process 1.2.3.0' v1.2.3.0` (you do have a gpg key, don't you? :)
3. lemme take a quick look if everything looks sensible
4. publish candidate into proper hackage release

**Comment by snoyberg** [comment]
First problem: I'm not a maintainer on Hackage :). I've tagged and signed
the tag, however.

**Comment by hvr** [comment]
@snoyberg you should be maintainer now...

**Comment by hvr** [comment]
@snoyberg I'm afraid you'll have to redo the tag, as I just saw that `changelog.md` still says "unreleased"

**Comment by snoyberg** [comment]
OK, new tag pushed. I'll be out of the house for the next few hours, so won't be able to upload as a proper Hackage release until I get back.

**Comment by hvr** [comment]
Well, I guess I'll trigger http://hackage.haskell.org/package/process-1.2.3.0/candidate/publish myself if everything checks out

**Comment by hvr** [comment]
@snoyberg everything looked good to me, so I I pressed the <kbd>publish candidate</kbd> button (which to my surprise let me show up as uploader -- @dcoutts is that by design that publishing a candidate resets the uploader-property?)

**Comment by Heather** [comment]
@snoyberg @hvr thank you.
