### ISSUE TITLE
bug in readProcessWithExitCode

### ISSUE THREAD

**Issue by chemist** [haskell/process#29]
in console
```bash
> touch empty_file
> chmod +x empty_file
>
> mkdir dir
> touch dir/empty_file
> chmod +x empty_file
>
```
then open repl
```haskell
> import System.Process
> readProcessWithExitCode "empty_file"  [] []
*** Exception: empty_file: readCreateProcessWithExitCode: runInteractiveProcess: exec: does not exist (No such file or directory)
``` 
it's ok

```haskell
> readProcessWithExitCode "dir/empty_file" [] []
(ExitSuccess,"","")
```
it's problem

used process-1.2.3.0

**Comment by snoyberg** [comment]
That's expected behavior, and depends on whether `.` is in your `PATH`. You can reproduce this at the shell yourself by running `empty_file` vs `dir/empty_file`.

**Comment by chemist** [comment]
```bash
➜  script-to-snmp  ./empty_file
zsh: exec format error: ./empty_file
➜  script-to-snmp  echo $?
126
```
but 
```haskell
> readProcessWithExitCode "./empty_file"  [] []
(ExitSuccess,"","")
```

**Comment by snoyberg** [comment]
Please elaborate, I don't know what your comment is intended to mean.

**Comment by chemist** [comment]
I execute empty script, and shell throw error with number 126,
but 
when i execute readProcessWithExitCode with this script, i don't see any error.
 As result i have (ExitSuccess, "", "").
Must be (ExitFailure 126, "", "")

**Comment by snoyberg** [comment]
I need to ask you to be much clearer in your reports. Is this the *same* bug you are reporting in the initial description, or is this in fact now a completely unrelated bug report?

**Comment by chemist** [comment]
unrelated, open other bug report?

**Comment by snoyberg** [comment]
That would have been better. However, I'm unable to reproduce your shell session anyway. Please come up with a clear reproducing case and then open a new issue. In my testing with both bash and zsh, executing a 0 length script results in a 0 exit code. I do not know how you're getting a 126.

**Comment by gregorycollins** [comment]
On my machine, zsh reports error 126 and bash silently succeeds. I think this is working as intended.

**Comment by snoyberg** [comment]
Interesting data point. @gregorycollins Are you on a Mac? I'm testing on Ubuntu with zsh 5.0.2. I wonder if there's a difference in behavior for either the OS or the version.

**Comment by chemist** [comment]
I think its oh-my-zsh problem or environment
```bash
➜  script-to-snmp  ./empty_file
zsh: exec format error: ./empty_file
➜  script-to-snmp  echo $?
126
➜  script-to-snmp  sh empty_file
➜  script-to-snmp  echo $?
0
➜  script-to-snmp  bash empty_file
➜  script-to-snmp  echo $?
0
➜  script-to-snmp  zsh empty_file
➜  script-to-snmp  echo $?
0
➜  script-to-snmp  echo $SHELL
/bin/zsh
```

**Comment by gregorycollins** [comment]
```
[greg@cronus:~]  [ 9:20AM]
λ  touch empty_file && chmod +x ./empty_file && ./empty_file; echo $?
zsh: exec format error: ./empty_file
126

[greg@cronus:~]  [ 9:21AM]
λ  zsh --version
zsh 5.0.0 (x86_64-apple-darwin11.4.1)

[greg@cronus:~]  [ 9:21AM]
λ  uname -a
Darwin cronus.local 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:25:48 PDT 2012; root:xnu-1699.32.7~1/RELEASE_X86_64 x86_64
```

**Comment by chemist** [comment]
```bash
[chemist@hw03]~% touch empty_file && chmod +x ./empty_file && ./empty_file; echo $?
zsh: Ошибка формата выполняемого файла: ./empty_file
126
[chemist@hw03]~% zsh --version
zsh 4.3.10 (x86_64-redhat-linux-gnu)
[chemist@hw03]~% uname -a
Linux hw03 3.10.30-1.el6.elrepo.x86_64 #1 SMP Fri Feb 14 12:50:15 EST 2014 x86_64 x86_64 x86_64 GNU/Linux
[chemist@hw03]~% /bin/zsh empty_file
[chemist@hw03]~% echo $?
0
```
