### ISSUE TITLE
readProcessWithExitCode is not a simple wrapper

### ISSUE THREAD

**Issue by noschinl** [haskell/process#3]
For 1.2.0.0, the documentation for readProcessWithExitCode states:

> readProcess and readProcessWithExitCode are fairly simple wrappers around createProcess. Constructing variants of these functions is quite easy: follow the link to the source code to see how readProcess is implemented.

However, while the implementation of these two functions is indeed quite easy, they depend on quite a number of module-internal functions -- a minimal copy readProcessWithExitCode takes around 100 lines of code. I would note call this "quite easy" anymore.

**Comment by dcoutts** [comment]
Indeed, they are not simple and we shouldn't advertise them as such. It's in fact all remarkably subtle.
