### ISSUE TITLE
Promote the `translate` function to the official API

### ISSUE THREAD

**Issue by pjones** [haskell/process#30]
The `translate` function is very useful for when you can't use one of the functions which accepts a command as a list.  For example, when the command you need to run is stored in a configuration file and you need to pass that string to the shell with additional arguments.  Having an official escaping function in these cases is essential.

**Comment by snoyberg** [comment]
The function is currently exposed from the .Internals module. I'm leaning towards saying we should leave it there, and not expose it from the primary module. In my experience, shell escaping functions are finicky at best, and I don't believe we want to have people rely on it. If you follow the code paths, it's actually currently getting almost no usage on non-Windows systems, for example, so I wouldn't be surprised if there are corner cases unaddressed.

**Comment by snoyberg** [comment]
Closing this issue. If there's some reason why working from the .Internals module is not acceptable, please reopen and explain.
