### ISSUE TITLE
install fail: System\Process\Internals.hs:149:9: Not in scope: `mkWeakMVar'

### ISSUE THREAD

**Issue by eflister** [haskell/process#35]
this is using latest minghc (GHC 7.10.1 32 bit) on win7/64, when trying to run "cabal install cabal-install"

**Comment by eflister** [comment]
latest version that didn't have this problem is 1.1.0.2

**Comment by snoyberg** [comment]
Can you report your GHC version and the version of process it's trying to
install?

**Comment by eflister** [comment]
OP says ghc 7.10.1, and the problem occurs with every version of process >1.1.0.2, starting with latest (1.2.3.0)

**Comment by snoyberg** [comment]
I didn't see that you edited the description after issue creation. I'll see if I can reproduce on my system.

**Comment by snoyberg** [comment]
I'm unable to reproduce so far. Can you include the output of both `ghc --version` and `cabal install cabal-install -v`?

**Comment by eflister** [comment]
hmm, i wiped the attempt and started over.  i think the problem may have been that i unknowingly had an earlier cabal installed, now it doesn't happen...
