### ISSUE TITLE
Feature request: Ability to change user and group

### ISSUE THREAD

**Issue by jprider63** [haskell/process#44]
I'd like to change the user and group of the forked process (I'm using Linux, but I think this would still make sense for Windows). I looked into implementing this myself, but it seems like there's extensive FFI use (ie `runInteractiveProcess`), and it could require some potentially breaking API changes. 

Do you think this is feasible?

**Comment by snoyberg** [comment]
When I've needed this I've always used `sudo`. I suppose adding some logic to the C part of the code to optionally call setuid and setgid should work. I can't think of a way to make this meaningful on Windows, however.

**Comment by jprider63** [comment]
I'm currently using a script to change the group and user, which then calls the target executable. I avoided using sudo because I need to explicitly control argv inputs and was concerned about the shell having to parse the arguments. 

For the API, maybe we could add two fields to `CreateProcess` called `child_user :: Maybe String` and `child_group :: Maybe String`. I could take a shot at implementing this if it seems reasonable to you.

**Comment by snoyberg** [comment]
Seems fine. My only question would be whether it should use a String or
expect Int (user ID). I'm fine either way.

Please note in the haddocks which OSs it's expected to work on.

**Comment by jprider63** [comment]
I just made a pull request with this implemented. I ended up going with `CGid` and `CUid` instead of `String`. I've only tested on unix with ghc, but I think other targets should be unaffected.

**Comment by snoyberg** [comment]
Implemented by PR #45, thank you!
