### ISSUE TITLE
Subprocess exits immediately when main process reads only stdout or only stderr

### ISSUE THREAD

**Issue by grayjay** [haskell/process#49]
Here is a simplified example:

    import System.Process
    import System.IO (hGetContents)
    
    main :: IO ()
    main = do
      let config = (shell "runhaskell ./Test.hs") {
                       std_out = CreatePipe
                     , std_err = CreatePipe
                     }
      (_, Just outh, Just errh, ph) <- createProcess config
      -- output <- hGetContents outh
      -- output <- hGetContents errh
      putStrLn $ "Output length: " ++ show (length output)
      code <- waitForProcess ph
      putStrLn $ "Exit code: " ++ show code

Test.hs:

    import Control.Monad
    import System.IO
    
    main = forever $ hPutStrLn stderr "1" >> hPutStrLn stdout "2"

When I uncomment the first commented line, the program prints this immediately:

    Output length: 768
    Exit code: ExitFailure 1

When I only uncomment the second commented line, it prints this:

    Output length: 736
    Exit code: ExitSuccess

The output lengths vary slightly by run.  When I use both handles or ignore both handles, the program doesn't stop, as expected.  I'm using Linux and GHC 7.10.2, and I observed the same behavior in process-1.2.3.0 and 1.4.0.0.

**Comment by snoyberg** [comment]
What makes you think this is behavior of process, add opposed to the program you're running?

**Comment by grayjay** [comment]
I don't think that the behavior I observed can be explained by the subprocess.  I can reproduce it more simply using `proc` and a C program, `infinite-loop`, as the subprocess:

    #include <stdio.h>
     
    int main() {
      while (1) {
        printf("2\n");
        fprintf(stderr, "1\n");
      }
    }

The behavior depends on whether the Haskell program keeps a reference to one of the output handles, which the subprocess shouldn't be able to detect.  In this example, the Haskell program only reads from stdout before waiting for the subprocess to terminate.  When I run the program as is, it prints a lot of 2's, prints `ExitFailure (-13)`, and exits.  When I uncomment the last line, which references stderr, it prints the 2's and then freezes.  I would expect it to freeze in both cases, because the pipe from stderr fills up.  I don't know if the bug is in the process library, but it seems likely.

    import System.Process
    import System.IO (hGetContents)
    
    main :: IO ()
    main = do
      let config = (proc "./infinite-loop" []) {
                       std_out = CreatePipe
                     , std_err = CreatePipe
                     }
      (_, Just outh, Just errh, ph) <- createProcess config
      output <- hGetContents outh
      putStrLn output
      code <- waitForProcess ph
      putStrLn $ "Exit code: " ++ show code
      -- errh `seq` return ()

**Comment by snoyberg** [comment]
I'm not really seeing the goal here, and the program you're providing is inherently buggy: it creates a pipe to the child process with a finite buffer, and never consumes from it. I'm surprised (and slightly impressed) that the almost-deadlock condition is detected (either by the Haskell code or the OS), but I don't consider this program a good test case. If you can demonstrate buggy behavior with properly written code, we can consider it a bug. But this current test case doesn't demonstrate anything to me.

**Comment by rwbarton** [comment]
I assume the GC eventually runs, and whichever file handle you don't retain a reference to gets closed when its finalizer runs. As a result the process eventually gets SIGPIPE for writing to a closed pipe.

**Comment by snoyberg** [comment]
Ah, good catch, thanks @rwbarton.

**Comment by rwbarton** [comment]
The analogous Python program doesn't behave the same way, even with an explicit close of the unused filehandle, but that is because Python ignores SIGPIPE and this setting is propagated to child processes. See http://www.chiark.greenend.org.uk/~cjwatson/blog/python-sigpipe.html. I doubt we want to do anything of this kind.

**Comment by grayjay** [comment]
@snoyberg @rwbarton  Thanks for looking into this.  Now I see that my original program had the same problem, so it's not an issue.  Is the exit code undefined behavior in this case?  I was surprised by the `ExitSuccess` in my first example.
