### ISSUE TITLE
buffering mode not preserved in UseHandle

### ISSUE THREAD

**Issue by ghorn** [haskell/process#53]
When I use `UseHandle` for `stdout` with a file handle, I expected the buffering mode to be preserved. Instead It is always set to `BlockBuffering`. Is this intended behavior?

**Comment by snoyberg** [comment]
Can you provide a test case demonstrating the problem?

**Comment by ghorn** [comment]
https://github.com/ghorn/process_buffering_example

**Comment by snoyberg** [comment]
This is expected behavior. Child processes inherit file descriptors, not
the Handles themselves. Buffering cannot be inherited by the child process.
