### ISSUE TITLE
system and rawSystem leak open FDs  O_o

### ISSUE THREAD

**Issue by DanielG** [haskell/process#55]
It looks like `system` doesn't close FDs like the equivalent from C would which is very surprising and a potentially security vulnerability.  

FdLeak.hs:

```
main = do
  h <- openFile "/tmp/foo" ReadWriteMode
  system "lvcreate"
  rawSystem "lvcreate" []
  hClose h
```

```
$ runhaskell FdLeak.hs
File descriptor 10 (/dev/tty) leaked on lvcreate invocation. Parent PID 5856: /bin/sh
File descriptor 11 (/tmp/foo) leaked on lvcreate invocation. Parent PID 5856: /bin/sh
[...]
File descriptor 10 (/dev/tty) leaked on lvcreate invocation. Parent PID 5847: /<somewhere>/ghc-7
File descriptor 11 (/tmp/foo) leaked on lvcreate invocation. Parent PID 5847: /<somewhere>/ghc-7
```

I'm just using lvcreate since I don't know any other program off the top off my head that warns on leaked FDs.

**Comment by snoyberg** [comment]
This is common behavior which has positive purposes (like passing a pipe between two processes). If you would like to avoid it, you need to use `close_fds` and drop to the `CreateProcess` API.

**Comment by DanielG** [comment]
I'm quite aware of that but shouldn't the unusual and potentially insecure use case (i.e. wanting to pass fds) be the one you have to drop to CreateProcess for?

Maybe it's just me but I think this behavior is crazy in a language that supposedly values safety as much as Haskell.

Say I have a Haskell program running as root which opens `/dev/mem`, then drops privileges and executes some program via `system`. A vulnerability in this program would suddenly give the attacker access to all system memory not really something I would expect from your standard `system` function.

**Comment by snoyberg** [comment]
Closing as wontdo

**Comment by DanielG** [comment]
I really think you should reconsider. At the _very_ least a warning in the documentation is in order.

**Comment by snoyberg** [comment]
PRs for documentation improvements are always welcomed and encouraged.

**Comment by DanielG** [comment]
I think the issue should remain open until this actually happens though.

**Comment by typetetris** [comment]
`system` from glibc doesn't close any fds.

You can request fds to be marked FD_CLOEXEC, then linux (even every posix unix) will close it for you on any exec* call. But you have to do so, either with specifying `O_CLOEXEC` on `open` or mode `e` on `fopen` and something similar for every other call allocating an fd.

So a parameter/flag to `openFile` to set `FD_CLOEXEC` would be more appropriate.

Can't tell anything about windows.
