### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by arianvp** [haskell/process#79]
Hello,

I'm currently trying to implement the following usecase:

1. I have a thread that spawns a process. the thread can timeout by `System.Timeout.timeout` and thus gets `ThreadKilled` thrown to it.
2. The spawned process should be `SIGTERM`'d 

Apparently, there is a function  `withCreateProcess` that has exactly these semantics. This function
is currently in `master` but has not been released yet. 
https://github.com/haskell/process/blob/master/System/Process.hs#L214

I was wondering if we could make a new release such that I can use this function?

**Comment by snoyberg** [comment]
Sure, I'll make the release on Sunday.

**Comment by arianvp** [comment]
Thank you!

**Comment by snoyberg** [comment]
OK, new release is up on Hackage (v1.4.3.0).
