### ISSUE TITLE
Clarify Binary properties of the streams

### ISSUE THREAD

**Issue by ndmitchell** [haskell/process#82]
The process library is largely silent on whether it gets binary or text handles to the process input/output. The one place where it is explicit is `runInteractiveCommand`, and there it seems to be wrong (as far as I can tell). I think this confusion has reared it's head as https://github.com/ndmitchell/hoogle/issues/194, https://github.com/commercialhaskell/stack/issues/2582, https://github.com/haskell/process/issues/59 and https://github.com/haskell/process/pull/36.

The command `ghc-pkg dump` is documented by GHC HQ to return UTF8 content, and to a first approximation, let's believe them (I have no reason to doubt it). If we install QuickCheck then the copyright field will include `Björn Bringert`. In Linux, if I set my `$LANG` variable to the empty string, then run the code:

```
import System.Process
import System.IO

main = do
    (inp,out,err,pid) <- runInteractiveCommand "ghc-pkg dump"
    hClose inp
    src <- hGetContents out
    print $ length src
```

With the command:

```
runhaskell -package=process-1.4.3.0 ProcessTest.hs
```

I get the output:

```
ProcessTest.hs: fd:13: hGetContents: invalid argument (invalid byte sequence)
```

If I leave the `$LANG` variable as normal (e.g. `en_GB.UTF-8`) then it works. That suggests the handles are impacted by the `$LANG` variable, and thus they aren't really binary. If I modify the code to add:

```
    hSetBinaryMode out True
```

Then it works once more.

It would be nice if there was a general statement at the top about whether the handles are in binary format or not, and it would be nice if the statements that were there were accurate.

**Comment by snoyberg** [comment]
I'd be happy if someone could send a PR with such improved docs. I'd have to ask someone more familiar to review the comments as well, but I _think_ what you're getting at here is true: all functions that get a `String` or `Text` out of the `Handle`s will default to the system locale.

**Comment by simonmar** [comment]
Yes, the Handles created by `createProcess` (and therefore everything defined in terms of it) are created as text Handles using the default locale encoding.

**Comment by ndmitchell** [comment]
So `runInteractiveCommand` has docs that are completely wrong. That comment was introduced in https://ghc.haskell.org/trac/ghc/ticket/2129, so 9 years ago it was in binary mode (confirmed with [the code](https://github.com/haskell/process/blob/3a8cf587eb1f8dd08c9599fe0632bea716618e5b/System/Process.hs#L232)), and that has changed since.

**Comment by simonmar** [comment]
Yeah, looks like it was me, when I added Unicode support to the IO library: https://github.com/haskell/process/commit/b3eb59a8ea062e8ea19a0b5aaf443607f3f8a3a0

We should just fix the docs.
