### ISSUE TITLE
process always uses sh

### ISSUE THREAD

**Issue by asr** [haskell/process#84]
I'm getting the following error with process-1.4.3.0 and Ubuntu:

```
$ echo $0
bash
```

```
$ ghc --numeric-version
8.0.2
```

```haskell
$ cat Test.hs
import System.Process

main :: IO ()
main = do
  _ <- createProcess (shell "diff <(ghc -V) <(ghc --numeric-version)")
  return ()
```

```
$ ghc Test.hs
$ ./Test
/bin/sh: 1: Syntax error: "(" unexpected
```

Note that I'm using `bash` but the error mentions `sh`. The error is due to the command 
```
diff <(ghc -V) <(ghc --numeric-version)
```
is accepted by `bash` but rejected by `sh`,  and `process` is using `sh`.

In https://github.com/simonmichael/shelltestrunner/issues/6#issuecomment-273642188, @simonmichael wrote:

> Unfortunately [process](http://hackage.haskell.org/package/process) hardcodes "/bin/sh" on POSIX (and "cmd" on Windows)

Why process is hard-coding `sh`?

CC'ing @jonaprieto.

**Comment by snoyberg** [comment]
For specifying a shell, I'd recommend replacing:

    shell foo

with

    proc ["bash", "-c", foo]

**Comment by rwbarton** [comment]
For comparison, the C `system` function and Python's `subprocess.call(cmd, shell=True)` also both hardcode `/bin/sh` as the shell. I think this is the expected behavior.

**Comment by asr** [comment]
IMO the expected behaviour should be to use the shell used for running the executable. Do you know some documentation supporting the current behaviour?

**Comment by simonmichael** [comment]
Predictability is probably considered preferable here. Eg in the case of https://github.com/simonmichael/shelltestrunner/issues/6, you wouldn't want test success depending on the current $SHELL preference of whoever happens to be running them.

**Comment by asr** [comment]
> Predictability is probably considered preferable here.

Yes, you are right.
