### ISSUE TITLE
createProcess treatment of cwd differs among OSs

### ISSUE THREAD

**Issue by jamescheney** [haskell/process#87]
If one calls createProcess with a cwd field for the child process set to a different directory than that of the parent process, different behavior is possible depending on the ambient OS.  I created a small example illustrating the problem.  

If you unzip the attached archive [bug.zip](https://github.com/haskell/process/files/735502/bug.zip) and run "test.sh", you should see something like this on a Linux system (I tried Ubuntu):

```
Parent process with cwd: /home/ubuntu/bug
Starting ./test/getcwd with cwd: /home/ubuntu/bug/test
Child process returned with value: ExitFailure 42
Return value of 42 indicates that the ambient OS looks for the executable in the child process's new CWD as set by createProcess.
```

On my (Mac/Darwin) system I see this instead:

```
Parent process with cwd: /Users/jcheney/tmp/bug
Starting ./getcwd with cwd: /Users/jcheney/tmp/bug/test
Child process returned with value: ExitFailure 17
Return value of 17 indicates that the ambient OS looks for the executable in the parent process's CWD.
```

(The values 17 and 42 are just random error return values chosen to differentiate the two possible child processes, which have identical filenames but different locations.)

This may not be a bug with System.Process per se, but rather an inconsistency in the behavior of vfork/fork or execvp(e) across systems.  Nevertheless in that case it might be helpful to document the fact that the current directory used to search for the executable inside createProcess is not reliable and to ensure portability an absolute path should be used.

**Comment by snoyberg** [comment]
Pinging @ezyang, this came up previously in #74. I had also been under the impression that behavior varied between OSes, but didn't have a test case to prove it. I thought there was more discussion that had occurred last time around, but I can't find it now. Edward: you have any additional memories to share?

**Comment by jamescheney** [comment]
Thanks.  I believe the test case I submitted demonstrates that the updated documentation added in 681aaee

> Relative paths are resolved with respect to 'cwd' if given, and otherwise the current working directory.

is not true on all OSs.

**Comment by ezyang** [comment]
When I added the comment, I just tested it on one OS and assumed that the behavior had been made to be consistent against OSes; @snoyberg then checked that this was actually true. I think it's perfectly possible that it's not consistent!

**Comment by snoyberg** [comment]
OK, cool, seems like we're all in agreement on the status quo then. I think the best we can do here is fixing the docs, changing the behavior is probably going to lead to ugly corner-cases and break existing code. @jamescheney do you see a different path forward? And if you agree, interested in sending a doc PR?

**Comment by jamescheney** [comment]
Sure I think it would be fine to modify the documentation so that it's clear that the behavior is implementation dependent (i.e. use absolute paths if you want to be portable).  That would have saved me a few hours of head-against-the-wall-banging.

**Comment by jamescheney** [comment]
Sure, see above.

**Comment by snoyberg** [comment]
Thank you!
