### ISSUE TITLE
Export CGid from System.Process.Internals (especially on Windows)

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/process#90]
I found myself wanting to derive some instances for `CreateProcess` in one of my applications recently, only to discover that it wouldn't work on Windows. Why? Because `CreateProcess` uses `UserID` and `GroupID` fields, the definitions of which are platform-dependent:

```haskell
#ifdef WINDOWS
-- Define some missing types for Windows compatibility. Note that these values
-- will never actually be used, as the setuid/setgid system calls are not
-- applicable on Windows. No value of this type will ever exist.
newtype CGid = CGid Word32
  deriving (Show, Eq)
type GroupID = CGid
type UserID = CGid
#else
type PHANDLE = CPid
#endif
```

This Windows-only newtype `CGid` is only available in the internal `System.Process.Common` module, and as a result, I can't make any instances for it (and thus can't derive any instances for `CreateProcess`).

Would you consider reexporting `CGid` from `System.Process.Internals`? That way I could accomplish my original goal, and `process` wouldn't have to make any API promises about the design of `CGid`.

**Comment by snoyberg** [comment]
I don't see too serious a downside here. Want to send a PR that you can
confirm fixes the problem for you?
