### ISSUE TITLE
Use the default linux shell for executing

### ISSUE THREAD

**Issue by KasperJanssens** [haskell/process#96]
My default shell is bash, however it seems that process uses 'sh' by default. 
Gabriel439/Haskell-Turtle-Library#234

**Comment by snoyberg** [comment]
This was discussed recently, please see #84.

**Comment by KasperJanssens** [comment]
Ah, yes, Google was not my friend, search terms too generic I suppose. Okay, I understand the reasons for hard coding /bin/sh. Might make a case for an explicit helper function that always uses bash because that's probably what will end up somewhere in a lot of client code I write now so as not to repeat the ["bash", "-c"] all the time, I guess. Don't know about the rest of the user base of course.

**Comment by snoyberg** [comment]
I think such a function would be too specific, and given the already
existing proliferation of variants of functions in the package, I'd rather
not add it.

**Comment by KasperJanssens** [comment]
I understand, I'll check whether the Turtle library would consider it a good function for them, if not I'll write my own shortcuts. The less strings to type the less I can mistype.
