### ISSUE TITLE
A 1.6.0.1 release?

### ISSUE THREAD

**Issue by bgamari** [haskell/process#99]
It would be helpful to get a quick 1.6.0.1 release as GHC 8.2.1 will need eedaff67abba546360bcff174c2dea58892d1e05. Let me know if there is anything I can do to help.

**Comment by snoyberg** [comment]
Will it cause a problem if this release is 1.6.1? There's a change on
master to export some identifiers from the internals module.

**Comment by bgamari** [comment]
Michael Snoyman <notifications@github.com> writes:

> Will it cause a problem if this release is 1.6.1? There's a change on
> master to export some identifiers from the internals module.
>
I think 1.6.1 should be fine.

Thanks for the quick response!

**Comment by snoyberg** [comment]
OK, should be done. Holler if I done goofed 😛

**Comment by capitanbatata** [comment]
Is there a release schedule for 1.6.1? We really need [this fix](https://github.com/haskell/process/pull/101) since we're using `turtle` (which in turn uses `process`) to launch external processes (for integration tests), and they cannot be killed on Windows platforms :(

**Comment by snoyberg** [comment]
1.6.1 has already been released, but I can make an extra release to include the fix in question.

**Comment by snoyberg** [comment]
OK, version 1.6.2.0 is now on Hackage.

**Comment by capitanbatata** [comment]
Thanks a lot! I just tested with the latest version, but it didn't fix [this issue](https://github.com/Gabriel439/Haskell-Turtle-Library/issues/255) 😭 , so I guess I have to report a new one.
